### ISSUE TITLE
Color Swatch and Theme Ideas

### ISSUE THREAD

**Issue by davidrodjen** [SpeakingInBits/LacamasFair#49]
Comment below, the number codes for a color swatch chosen for the website. Please include a few ideas for styling or changes that would increase site usability and appearance.

**Comment by CourtneyHutchin** [comment]
Here is a color palette I have put together. Please let me know if you have any suggestions for changes.

- Background Color: #4E6172
- Accent Color: #9DDB5A
- Text Color: #FFFFFF
- Textbox Color: #3D4954

![LacamasFair](https://user-images.githubusercontent.com/50035291/74484386-4ab50300-4e6d-11ea-84cd-1e14e8512d66.png)

**Comment by davidrodjen** [comment]
Looks awesome! Great job! Earth tones seem to be close to a winning choice for the site.
