### ISSUE TITLE
Implement more add/update/delete options for admins only

### ISSUE THREAD

**Issue by KarloParagas** [SpeakingInBits/LacamasFair#85]
User(s) with admin credentials should have the ability to update announcements, upcoming events, fair board members, annual harvest festival, and annual christmas bazaar.

**Comment by JoeProgrammer88** [comment]
@KarloParagas you should close this and make separate issues for each of the items. Announcements/Board Members/Events/ etc.

**Comment by KarloParagas** [comment]
Closing this issue to make separate issues for each items.
